[package]
name = "wamp-final"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version="1.0.188", features = ["derive"]}
serde_json = "1.0.107"
regex = "1.9.5"
serde_repr = "0.1.16"
